#!/usr/bin/env python3
import sys

from typex import TypeX
from stator import Stator
from rotor import Rotor

def read_file(file_name):
    return open(file_name, 'r').read()

def main():

    typex = TypeX(encryptors=[
        Stator(wiring='THELAZYBROWNFXJUMPSVQICKDG', initial_position=0),
        Stator(wiring='ABCDEFOPQGHIJKLMNRSTXYZUVW', initial_position=3),
        Rotor(wiring='QWERTYUIOPASDFGHJKLZXCVBNM', initial_position=4, notchings=[0,5,12,16,25]),
        Rotor(wiring='HELOWRDQTYUIPASFGJKZXCVBNM', initial_position=2, notchings=[3,4,6,10]),
        Rotor(wiring='TMJKLQNSAPBUGCVRZWYHDEFOIX', initial_position=7)
    ])

    # Read in all of the lines from file names
    # specified in argument list or from stdin
    if len(sys.argv) >= 2:
        input_text = ''.join(map(read_file, sys.argv[1:]))
    else:
        input_text = sys.stdin.read()

    # Encode the text from stdin
    encrypted_text = typex.encrypt(input_text)

    # Print the result to stdout
    print(''.join(encrypted_text))

if __name__ == '__main__':
    main()
